Implementation of Minimal Encoding Method
Jij-Inc/JijModelingTranspilerQuantum pull request #19
Opened 2023-08-21 11:46 UTC by Jacomichi

# Added Feature:
I have implemented the minimal encoding method. Unlike the conventional VQE, we do not use the measurement result itself as the cost function. Instead, we use a function defined based on the measurement results. To include features such as cost function generation, I have designed it such that we create a `MinimalEncodedInstance` from the `MinimalEncodingBuilder`, and then utilize this instance to extract the cost function and obtain the final results.

# Concerns:
With the above-described structure, it deviates from the form of other algorithms. I would appreciate any advice or feedback on this aspect.

2023-08-22 01:53 UTC, yuyamashiro requested changes
たぶん僕も同じような構成にすると思います。構成はこれで問題ないです。
しかし他の関数と出力が異なるので、Minimal encodingの概要をどこかのDocstringに書いて、なんでminimized functionが出力されるのかは書いた方がいい気がします。

2023-08-22 01:57 UTC, Jacomichi commented
コメントありがとうございます！

構成はこのままで、minimal encodingの概要を詳細に説明するという方針で進めたいと思います.

2023-08-23 09:26 UTC, Jacomichi commented on jijmodeling_transpiler_quantum/qiskit/minimal_encoding/to_minimal_encoding.py
> +            but also for the calculation of expected values and the subsequent calculation of the cost function.
minimal encodingのコスト関数に関する説明として、こちらを追加しました。

2023-08-23 09:26 UTC, Jacomichi commented
docstringの修正を行いました。

2023-09-08 01:00 UTC, yuyamashiro approved these changes

2023-09-08 01:00 UTC, merged